-- MySQL Script generated by aleon
-- 16 abril 2022

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema artesapp
-- -----------------------------------------------------
/*borra schema si existeix*/
DROP SCHEMA IF EXISTS artesapp;

CREATE SCHEMA IF NOT EXISTS artesapp DEFAULT CHARACTER SET utf8mb4 ;
USE artesapp ;

/*user*/
DROP USER IF EXISTS 'artesapp'@'%';
CREATE USER 'artesapp'@'%' IDENTIFIED BY '1234';

/*GRANT type_of_permission ON database_name.table_name TO 'username'@'localhost';*/

GRANT ALL PRIVILEGES ON artesapp.* TO 'artesapp'@'%' with grant option;
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'artesapp'@'%';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
